apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
# Los valores deben estar en Base64. Ejemplo de cómo codificar:
#   echo -n "mi_valor" | base64
#
# Reemplaza los valores por los tuyos codificados en Base64:
#   DB_HOST  : aws-1-us-east-2.pooler.supabase.com
#   DB_USER  : postgres.uggdzczccgozznhqqawg
#   DB_PASSWORD: Admin12345vg...
data:
  DB_HOST: YXdzLTEtdXMtZWFzdC0yLnBvb2xlci5zdXBhYmFzZS5jb20=
  DB_USER: cG9zdGdyZXMudWdnZHpjemNjZ296em5ocXFhd2c=
  DB_PASSWORD: QWRtaW4xMjM0NXZnLi4u
